version: "3"

services:
  app:
    image: tezusecommerce/nginx
    ports:
      - "80:8000"
      - "443:8443"
    links:
      - db
      - phpfpm
    volumes: &appvolumes
      - ~/.composer:/var/www/.composer:cached
      - appdata:/var/www/html
      - sockdata:/sock
      - ssldata:/etc/nginx/certs
    deploy:
      resources:
        limits:
          memory: 512M

  phpfpm:
    image: tezusecommerce/php7.3
    links:
      - db
    volumes: *appvolumes

  db:
    image: percona:5.7
    command: --max_allowed_packet=64M
    ports:
      - "3306:3306"
    env_file: env/db.env
    volumes:
      - dbdata:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 512M

  redis:
    image: redis:5.0-alpine
    deploy:
      resources:
        limits:
          memory: 512M

  elasticsearch:
    image: tezusecommerce/elasticsearch6
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
    deploy:
      resources:
        limits:
          memory: 512M

  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    deploy:
      resources:
        limits:
          memory: 512M

volumes:
  appdata:
  dbdata:
  rabbitmqdata:
  sockdata:
  ssldata:
